version: '3.7'

services:
  postgres:
    image: postgres:alpine
    environment:
      TZ: "Asia/Jakarta"
      PGTZ: "Asia/Jakarta"
      POSTGRES_DB: kompas
      POSTGRES_PASSWORD: password
      POSTGRES_USER: kompas
      PGDATA: /var/lib/postgresql/data/kompas
    container_name: postgres
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
  frontend:
    image: nginx
    volumes:
      - ./config.conf:/etc/nginx/conf.d/default.conf
      - ./build:/usr/share/nginx/html:rw
    links:
        - backend
    ports:
      - "8080:80"
  backend:
      build: .
      volumes:
        - ./files/var/kompas:/opt/kompas:rw
      environment:
        ACCESS_SECRET: 1n14d1l1h53bu4hs3cr3t
        REFRESH_SECRET: 1n14d1l1h53bu4hs3cr3t
      ports:
          - 1318:1318
      links:
        - postgres
        - redis